import { DecimalPipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Unit { unitId:number; unitNumber:string; isActive:boolean; }
interface AdditionalCharge { additionalChargeId:number; unitId:number; unitNumber:string; billingPeriod:string; category:string; description:string; amount:number; source:string; status:string; createdAt:string; }

@Component({
  selector:'app-additional-charges', standalone:true, imports:[FormsModule, DecimalPipe],
  template:`
    <section class="panel create"><div class="head"><div><h2>Add facility or service charge</h2><p>Temporary admin entry point until the Facility system sends charges automatically.</p></div></div>
      <div class="form"><label>Billing period<input type="month" [(ngModel)]="form.billingPeriod" min="2020-01" max="2100-12"></label><label>Unit<select [(ngModel)]="form.unitId"><option [ngValue]="0">Choose a unit</option>@for(unit of units;track unit.unitId){<option [ngValue]="unit.unitId">{{unit.unitNumber}}</option>}</select></label><label>Charge category<select [(ngModel)]="form.category"><option value="">Choose a category</option>@for(category of categories;track category){<option>{{category}}</option>}</select></label><label>Amount (RM)<input type="number" min="0.01" max="999999.99" step="0.01" [(ngModel)]="form.amount"></label>@if(form.category==='Other service'){<label class="service-name">Service name <span>(required)</span><input maxlength="80" placeholder="e.g. Moving-in deposit" [(ngModel)]="form.serviceName"></label>}<label class="description">Description <span>(optional)</span><input maxlength="250" placeholder="e.g. July parking bay rental" [(ngModel)]="form.description"></label><button (click)="create()" [disabled]="saving">{{saving?'Adding...':'Add pending charge'}}</button></div>
      @if(message){<p class="message" [class.error]="isError">{{message}}</p>}</section>
    <section class="panel"><div class="head"><div><h2>Additional charges</h2><p>Pending charges are included only on the selected unit's bill for the matching period.</p></div><button class="outline" (click)="load()">Refresh</button></div>
      <div class="toolbar"><input [(ngModel)]="query" placeholder="Search unit, category, or billing period..."><select [(ngModel)]="statusFilter"><option value="All">All statuses</option><option value="Pending">Pending</option><option value="Billed">Billed</option><option value="Cancelled">Cancelled</option></select></div>
      @if(loading){<p class="empty">Loading additional charges...</p>} @else if(!filtered.length){<p class="empty">No additional charges match this filter.</p>} @else {<div class="table-wrap"><table><thead><tr><th>Unit</th><th>Billing period</th><th>Category</th><th>Description</th><th>Amount</th><th>Source</th><th>Status</th><th>Action</th></tr></thead><tbody>@for(charge of filtered;track charge.additionalChargeId){<tr><td><b>{{charge.unitNumber}}</b></td><td>{{charge.billingPeriod}}</td><td>{{charge.category}}</td><td>{{charge.description}}</td><td>RM {{charge.amount|number:'1.2-2'}}</td><td>{{charge.source}}</td><td><span class="status" [class.billed]="charge.status==='Billed'" [class.cancelled]="charge.status==='Cancelled'">{{charge.status}}</span></td><td>@if(charge.status==='Pending'){<button class="cancel" (click)="cancel(charge)" [disabled]="cancellingId===charge.additionalChargeId">{{cancellingId===charge.additionalChargeId?'Cancelling...':'Cancel'}}</button>} @else {<span class="na">—</span>}</td></tr>}</tbody></table></div>}</section>
  `,
  styles:[`:host{display:block}.panel{margin-top:26px;padding:22px;background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:20px;align-items:end}.form label{display:grid;gap:7px;color:#91a0b8;font-size:.78rem;font-weight:700}.form label span{font-weight:400}.form input,.form select,.toolbar input,.toolbar select{box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.form input[type=month]{color-scheme:dark}.form input[type=number]{appearance:textfield}.form input[type=number]::-webkit-inner-spin-button,.form input[type=number]::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}.description,.service-name{grid-column:span 2}.form button{border:0;border-radius:8px;padding:11px 15px;background:#347cf2;color:#fff;font-weight:700;cursor:pointer}.form button:disabled,.cancel:disabled{opacity:.65;cursor:wait}.message{margin:15px 0 0;color:#47dca8;font-weight:700;font-size:.85rem}.message.error{color:#ff9292}.outline{background:transparent;border:1px solid #3b4d6b;color:#a9c5f7;border-radius:8px;padding:10px 14px;font-weight:700;cursor:pointer}.toolbar{display:flex;gap:12px;margin:22px 0}.toolbar input{flex:1}.toolbar select{max-width:190px}.table-wrap{overflow:auto}table{width:100%;min-width:950px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}td b{color:#72a8ff}.status{display:inline-block;padding:4px 9px;border-radius:10px;background:#493a18;color:#ffc75d;font-size:.77rem}.status.billed{background:#103b30;color:#47dca8}.status.cancelled{background:#303846;color:#adb9ca}.cancel{border:1px solid #70343b;border-radius:7px;padding:7px 10px;background:transparent;color:#ff9999;font-size:.77rem;font-weight:700;cursor:pointer}.na{color:#71819a}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:920px){.form{grid-template-columns:repeat(2,1fr)}.description,.service-name{grid-column:span 1}}@media(max-width:560px){.form,.toolbar{grid-template-columns:1fr;display:grid}.toolbar select{max-width:none}}`]
})
export class AdditionalChargesComponent implements OnChanges {
  @Input({required:true}) token=''; units:Unit[]=[]; charges:AdditionalCharge[]=[]; categories=['Parking','Badminton court','Gym','Multipurpose hall','Swimming pool','Access card','Other service']; form={billingPeriod:this.currentPeriod(),unitId:0,category:'Parking',amount:0,serviceName:'',description:''}; query=''; statusFilter='All'; loading=false; saving=false; cancellingId:number|null=null; message=''; isError=false;
  constructor(private http:HttpClient){}
  ngOnChanges(){if(this.token){this.loadUnits();this.load()}}
  private headers(){return new HttpHeaders({Authorization:`Bearer ${this.token}`})}
  private currentPeriod(){const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
  get filtered(){const value=this.query.trim().toLowerCase();return this.charges.filter(charge=>(this.statusFilter==='All'||charge.status===this.statusFilter)&&(!value||`${charge.unitNumber} ${charge.category} ${charge.description} ${charge.billingPeriod}`.toLowerCase().includes(value)))}
  loadUnits(){this.http.get<Unit[]>('http://localhost:5112/api/admin/properties/units',{headers:this.headers()}).subscribe({next:units=>this.units=units.filter(unit=>unit.isActive)})}
  load(){this.loading=true;this.http.get<AdditionalCharge[]>('http://localhost:5112/api/admin/additional-charges',{headers:this.headers()}).subscribe({next:charges=>{this.charges=charges;this.loading=false},error:()=>{this.loading=false;this.message='Unable to load additional charges. Restart the backend after applying the database migration.';this.isError=true}})}
  create(){if(!/^\d{4}-\d{2}$/.test(this.form.billingPeriod)||!this.form.unitId||!this.form.category||Number(this.form.amount)<=0){this.message='Choose a period, unit, category, and an amount greater than RM 0.00.';this.isError=true;return}if(this.form.category==='Other service'&&!this.form.serviceName.trim()){this.message='Enter a service name for Other service.';this.isError=true;return}const description=this.form.category==='Other service'?this.form.serviceName.trim()+(this.form.description.trim()?`: ${this.form.description.trim()}`:''):this.form.description;this.saving=true;this.message='';this.http.post<AdditionalCharge>('http://localhost:5112/api/admin/additional-charges',{...this.form,description},{headers:this.headers()}).subscribe({next:()=>{this.saving=false;this.message='Additional charge added. It will be included when bills for this period are generated.';this.isError=false;this.form.amount=0;this.form.serviceName='';this.form.description='';this.load()},error:error=>{this.saving=false;this.message=error.error?.message||'Unable to add the additional charge.';this.isError=true}})}
  cancel(charge:AdditionalCharge){if(!window.confirm(`Cancel the ${charge.category} charge for ${charge.unitNumber}?`))return;this.cancellingId=charge.additionalChargeId;this.http.post(`http://localhost:5112/api/admin/additional-charges/${charge.additionalChargeId}/cancel`,{},{headers:this.headers()}).subscribe({next:()=>{this.cancellingId=null;this.message='Additional charge cancelled.';this.isError=false;this.load()},error:error=>{this.cancellingId=null;this.message=error.error?.message||'Unable to cancel the additional charge.';this.isError=true}})}
}
