import { DatePipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Audit { adminUsername:string; actionType:string; affectedEntity:string; affectedEntityId?:number; description?:string; timestamp:string; }

@Component({
  selector:'app-audit-log',standalone:true,imports:[DatePipe,FormsModule],
  template:`
    <section class="metrics"><article><span>Recorded actions</span><strong>{{logs.length}}</strong><small>Latest available records</small></article><article><span>Created records</span><strong class="blue">{{createCount}}</strong><small>Units and billing items</small></article><article><span>Payment reviews</span><strong class="green">{{reviewCount}}</strong><small>Confirmed or rejected proofs</small></article><article><span>Active admins</span><strong class="purple">{{adminCount}}</strong><small>In current log history</small></article></section>
    <section class="panel"><div class="head"><div><h2>Audit log</h2><p>Read-only record of administrative actions across the platform.</p></div><button class="outline" (click)="load()">Refresh</button></div><div class="toolbar"><input [(ngModel)]="query" placeholder="Search admin, action, or description..."><select [(ngModel)]="actionFilter"><option value="All">All actions</option><option value="Create">Create</option><option value="Review">Review</option></select></div>@if(loading){<p class="empty">Loading audit records...</p>}@else if(!filtered.length){<p class="empty">No audit records match this filter.</p>}@else{<div class="table-wrap"><table><thead><tr><th>Time</th><th>Admin</th><th>Action</th><th>Record</th><th>Description</th></tr></thead><tbody>@for(log of filtered;track log.timestamp+log.description){<tr><td class="time">{{log.timestamp|date:'medium'}}</td><td><span class="admin">{{log.adminUsername}}</span></td><td><span class="action" [class.review]="log.actionType==='Review'">{{log.actionType}}</span></td><td>{{log.affectedEntity}}{{log.affectedEntityId?' #'+log.affectedEntityId:''}}</td><td>{{log.description||'No description provided.'}}</td></tr>}</tbody></table></div>}</section>
  `,
  styles:[`
    :host{display:block}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:26px 0}.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.metrics article{padding:19px}.metrics span,.metrics small{display:block;color:#8fa0ba;font-size:.8rem}.metrics strong{display:block;color:#edf3ff;font-size:1.45rem;margin:13px 0 5px}.metrics .blue{color:#69a4ff}.metrics .green{color:#42d9a3}.metrics .purple{color:#b49bff}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.head button{border:0;border-radius:8px;padding:11px 15px;font-weight:700;cursor:pointer}.head .outline{background:transparent;border:1px solid #3b4d6b;color:#a9c5f7}.toolbar{display:flex;gap:12px;margin:22px 0}.toolbar input,.toolbar select{box-sizing:border-box;padding:11px 12px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.toolbar input{flex:1}.toolbar select{min-width:170px}.table-wrap{overflow:auto}table{width:100%;min-width:860px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7;vertical-align:middle}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}.time{color:#8ea0b9;font-family:ui-monospace,monospace;font-size:.78rem}.admin{display:inline-block;padding:4px 9px;border-radius:10px;background:#1d365e;color:#78adff;font-size:.78rem}.action{display:inline-block;padding:4px 9px;border-radius:10px;background:#403318;color:#ffc75d;font-size:.77rem}.action.review{background:#103b30;color:#47dca8}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.metrics{grid-template-columns:1fr}.head,.toolbar{align-items:flex-start;flex-direction:column}.toolbar input,.toolbar select{width:100%}}
  `]
})
export class AuditLogComponent implements OnChanges {
  @Input({required:true}) token='';logs:Audit[]=[];loading=false;query='';actionFilter='All';
  constructor(private http:HttpClient){}
  ngOnChanges(){this.load()}
  get filtered(){const value=this.query.trim().toLowerCase();return this.logs.filter(log=>(this.actionFilter==='All'||log.actionType===this.actionFilter)&&(!value||`${log.adminUsername} ${log.actionType} ${log.affectedEntity} ${log.description||''}`.toLowerCase().includes(value)))}
  get createCount(){return this.logs.filter(log=>log.actionType==='Create').length}get reviewCount(){return this.logs.filter(log=>log.actionType==='Review').length}get adminCount(){return new Set(this.logs.map(log=>log.adminUsername)).size}
  load(){if(!this.token)return;this.loading=true;this.http.get<Audit[]>('http://localhost:5112/api/admin/audit-log',{headers:new HttpHeaders({Authorization:`Bearer ${this.token}`})}).subscribe({next:data=>{this.logs=data;this.loading=false},error:()=>this.loading=false})}
}
