import { DecimalPipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface BillingItem { billingItemId: number; chargeType: string; defaultRate: number; frequency: string; billingDay: number; dueDay: number; penaltyRate: number; gracePeriodDays: number; isActive: boolean; }

@Component({
  selector: 'app-billing-configuration', standalone: true, imports: [FormsModule, DecimalPipe],
  template: `
    <section class="metrics"><article><span>Total charge types</span><strong>{{ items.length }}</strong></article><article><span>Active items</span><strong class="green">{{ activeCount }}</strong></article><article><span>Monthly charges</span><strong class="blue">{{ monthlyCount }}</strong></article><article><span>Average rate</span><strong class="orange">RM {{ averageRate | number:'1.2-2' }}</strong></article></section>
    <section class="panel"><div class="head"><div><h2>Billing items</h2><p>Manage charge types and rates used for bill generation.</p></div><button (click)="showForm = !showForm">{{ showForm ? 'Cancel' : '+ Add billing item' }}</button></div>
      @if (showForm) {<form class="item-form" (ngSubmit)="add()"><div class="field"><label for="charge-type">Charge type</label><input id="charge-type" [(ngModel)]="draft.chargeType" name="chargeType" placeholder="e.g. Maintenance Fee" required></div><div class="field"><label for="default-rate">Default rate (RM)</label><input id="default-rate" [(ngModel)]="draft.defaultRate" name="defaultRate" type="number" min="0" step="0.01" required></div><div class="field"><label for="frequency">Billing frequency</label><select id="frequency" [(ngModel)]="draft.frequency" name="frequency"><option>Monthly</option><option>Quarterly</option><option>Yearly</option></select></div><div class="field"><label for="billing-day">Billing day (1-31)</label><input id="billing-day" [(ngModel)]="draft.billingDay" name="billingDay" type="number" min="1" max="31" required></div><div class="field"><label for="due-day">Due day (1-31)</label><input id="due-day" [(ngModel)]="draft.dueDay" name="dueDay" type="number" min="1" max="31" required></div><div class="field"><label for="penalty-rate">Penalty rate (%)</label><input id="penalty-rate" [(ngModel)]="draft.penaltyRate" name="penaltyRate" type="number" min="0" max="100" step="0.01"></div><div class="field"><label for="grace-period">Grace period (days)</label><input id="grace-period" [(ngModel)]="draft.gracePeriodDays" name="gracePeriodDays" type="number" min="0" max="365"></div><button [disabled]="saving">{{ saving ? 'Saving...' : 'Save billing item' }}</button></form>}
      @if(message){<p class="message" [class.error]="isError">{{message}}</p>}
      <div class="toolbar"><input [(ngModel)]="query" placeholder="Search charge types..."><span>{{ filtered.length }} item{{ filtered.length === 1 ? '' : 's' }} shown</span></div>
      @if(loading){<p class="empty">Loading billing items...</p>} @else if(!filtered.length){<p class="empty">No billing items match your search.</p>} @else {<div class="table-wrap"><table><thead><tr><th>Charge type</th><th>Default rate</th><th>Frequency</th><th>Billing day</th><th>Due day</th><th>Penalty</th><th>Status</th></tr></thead><tbody>@for(item of filtered;track item.billingItemId){<tr><td><b>{{item.chargeType}}</b></td><td>RM {{item.defaultRate|number:'1.2-2'}}</td><td><span class="frequency" [class.quarterly]="item.frequency==='Quarterly'" [class.yearly]="item.frequency==='Yearly'">{{item.frequency}}</span></td><td>{{ordinal(item.billingDay)}} of month</td><td>{{ordinal(item.dueDay)}} of month</td><td>{{item.penaltyRate}}%</td><td><span class="status" [class.inactive]="!item.isActive">{{item.isActive?'Active':'Inactive'}}</span></td></tr>}</tbody></table></div>}
    </section>
  `,
  styles:[`
    :host{display:block}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:26px 0}.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.metrics article{padding:19px}.metrics span{display:block;color:#8fa0ba;font-size:.8rem}.metrics strong{display:block;color:#edf3ff;font-size:1.55rem;margin-top:13px}.metrics .green{color:#42d9a3}.metrics .blue{color:#69a4ff}.metrics .orange{color:#ffbf55}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.head button,.item-form button{border:0;border-radius:8px;padding:11px 15px;background:#347cf2;color:#fff;font-weight:700;cursor:pointer}.item-form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;align-items:end;margin-top:20px;padding:16px;background:#121927;border:1px solid #2a3854;border-radius:10px}.item-form .field{display:grid;gap:7px;color:#91a0b8;font-size:.78rem;font-weight:700}.item-form input,.item-form select,.toolbar input{box-sizing:border-box;width:100%;padding:11px 12px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.item-form input[type=number]{appearance:textfield}.item-form input[type=number]::-webkit-inner-spin-button,.item-form input[type=number]::-webkit-outer-spin-button{appearance:none;margin:0}.item-form button:disabled{opacity:.6}.message{margin:15px 0;color:#47dca8;font-size:.85rem;font-weight:700}.message.error{color:#ff9292}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-top:22px;padding:12px 0}.toolbar input{max-width:365px}.toolbar span{color:#8293ae;font-size:.8rem}.table-wrap{overflow:auto}table{width:100%;min-width:850px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}td b{color:#eef4ff}.frequency,.status{display:inline-block;padding:4px 9px;border-radius:10px;font-size:.77rem}.frequency{background:#1d365e;color:#78adff}.frequency.quarterly{background:#49340e;color:#ffc75d}.frequency.yearly{background:#352660;color:#b6a0ff}.status{background:#103b30;color:#47dca8}.status.inactive{background:#41262b;color:#ff9999}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.item-form{grid-template-columns:1fr 1fr}}@media(max-width:560px){.metrics,.item-form{grid-template-columns:1fr}.head,.toolbar{align-items:flex-start;flex-direction:column}.toolbar input{max-width:none}}
  `]
})
export class BillingConfigurationComponent implements OnChanges {
  @Input({required:true}) token=''; items:BillingItem[]=[]; query=''; loading=false; saving=false; showForm=false; message=''; isError=false;
  draft={chargeType:'',defaultRate:0,frequency:'Monthly',billingDay:1,dueDay:15,penaltyRate:0,gracePeriodDays:0};
  constructor(private http:HttpClient){}
  ngOnChanges(){if(this.token)this.load()}
  private headers(){return new HttpHeaders({Authorization:`Bearer ${this.token}`})}
  get filtered(){const value=this.query.trim().toLowerCase();return value?this.items.filter(item=>item.chargeType.toLowerCase().includes(value)):this.items}
  get activeCount(){return this.items.filter(item=>item.isActive).length}
  get monthlyCount(){return this.items.filter(item=>item.frequency==='Monthly').length}
  get averageRate(){return this.items.length?this.items.reduce((sum,item)=>sum+item.defaultRate,0)/this.items.length:0}
  ordinal(value:number){const suffix=value%10===1&&value%100!==11?'st':value%10===2&&value%100!==12?'nd':value%10===3&&value%100!==13?'rd':'th';return `${value}${suffix}`}
  load(){this.loading=true;this.http.get<BillingItem[]>('http://localhost:5112/api/admin/billing-items',{headers:this.headers()}).subscribe({next:items=>{this.items=items;this.loading=false},error:()=>{this.message='Unable to load billing items.';this.isError=true;this.loading=false}})}
  add(){this.saving=true;this.message='';this.http.post('http://localhost:5112/api/admin/billing-items',this.draft,{headers:this.headers()}).subscribe({next:()=>{this.saving=false;this.showForm=false;this.draft={chargeType:'',defaultRate:0,frequency:'Monthly',billingDay:1,dueDay:15,penaltyRate:0,gracePeriodDays:0};this.message='Billing item added successfully.';this.isError=false;this.load()},error:error=>{this.saving=false;this.message=error.status===409?'This charge type already exists.':'Unable to save billing item.';this.isError=true}})}
}
