import { DatePipe, DecimalPipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Bill { billId: number; referenceNumber: string; unitNumber: string; billingPeriod: string; dueDate: string; totalAmount: number; outstandingBalance: number; status: string; }

@Component({
  selector: 'app-bills', standalone: true, imports: [FormsModule, DecimalPipe, DatePipe],
  template: `
    <section class="run-panel"><div><h2>Billing run configuration</h2><p>Create one itemised bill for every active unit using the current billing configuration.</p></div><div class="run-form"><label>Billing period<input [(ngModel)]="period" placeholder="YYYY-MM"></label><label>Due date<input [(ngModel)]="dueDate" type="date"></label><button (click)="generate()" [disabled]="generating">{{ generating ? 'Generating...' : 'Generate bills' }}</button></div>@if(message){<p class="message" [class.error]="isError">{{message}}</p>}</section>
    <section class="metrics"><article><span>Bills generated</span><strong>{{ bills.length }}</strong><small>All billing periods</small></article><article><span>Total amount</span><strong class="blue">RM {{ totalAmount | number:'1.2-2' }}</strong><small>Across all bills</small></article><article><span>Outstanding</span><strong class="orange">RM {{ outstanding | number:'1.2-2' }}</strong><small>Unpaid balance</small></article><article><span>Paid bills</span><strong class="green">{{ paidCount }}</strong><small>Confirmed collections</small></article></section>
    <section class="panel"><div class="head"><div><h2>Generated bills</h2><p>Search and review every bill in the property.</p></div><button class="outline" (click)="load()">Refresh</button></div><div class="toolbar"><input [(ngModel)]="query" placeholder="Search reference or unit..."><select [(ngModel)]="statusFilter"><option value="All">All statuses</option><option value="Paid">Paid</option><option value="Unpaid">Unpaid</option><option value="Overdue">Overdue</option><option value="ProofSubmitted">Proof submitted</option></select></div>@if(loading){<p class="empty">Loading bills...</p>} @else if(!filtered.length){<p class="empty">No bills match this filter.</p>} @else {<div class="table-wrap"><table><thead><tr><th>Bill reference</th><th>Unit</th><th>Billing period</th><th>Due date</th><th>Total due</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>@for(bill of filtered;track bill.billId){<tr><td><b>{{bill.referenceNumber}}</b></td><td>{{bill.unitNumber}}</td><td>{{bill.billingPeriod}}</td><td>{{bill.dueDate|date:'mediumDate'}}</td><td>RM {{bill.totalAmount|number:'1.2-2'}}</td><td [class.alert]="bill.outstandingBalance>0">RM {{bill.outstandingBalance|number:'1.2-2'}}</td><td><span class="status" [class.paid]="bill.status==='Paid'" [class.overdue]="bill.status==='Overdue'" [class.proof]="bill.status==='ProofSubmitted'">{{bill.status}}</span></td></tr>}</tbody></table></div>}</section>
  `,
  styles:[`
    :host{display:block}.run-panel,.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.run-panel{margin-top:26px;padding:22px}.run-panel h2,.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.run-panel p,.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.run-form{display:flex;gap:12px;align-items:end;margin-top:20px}.run-form label{display:grid;gap:7px;color:#91a0b8;font-size:.78rem;font-weight:700}.run-form input,.toolbar input,.toolbar select{box-sizing:border-box;padding:11px 12px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.run-form button,.head button{border:0;border-radius:8px;padding:11px 15px;background:#347cf2;color:#fff;font-weight:700;cursor:pointer}.run-form button:disabled{opacity:.6}.message{margin:15px 0 0;color:#47dca8;font-size:.85rem;font-weight:700}.message.error{color:#ff9292}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:18px 0}.metrics article{padding:19px}.metrics span,.metrics small{display:block;color:#8fa0ba;font-size:.8rem}.metrics strong{display:block;color:#edf3ff;font-size:1.45rem;margin:13px 0 5px}.metrics .green{color:#42d9a3}.metrics .blue{color:#69a4ff}.metrics .orange{color:#ffbf55}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head .outline{background:transparent;border:1px solid #3b4d6b;color:#a9c5f7}.toolbar{display:flex;gap:12px;margin:22px 0}.toolbar input{flex:1}.toolbar select{min-width:170px}.table-wrap{overflow:auto}table{width:100%;min-width:840px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}td b{color:#72a8ff}.alert{color:#ff9a9a}.status{display:inline-block;padding:4px 9px;border-radius:10px;background:#493a18;color:#ffc75d;font-size:.77rem}.status.paid{background:#103b30;color:#47dca8}.status.overdue{background:#51262b;color:#ff9999}.status.proof{background:#1d365e;color:#78adff}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}.run-form{flex-wrap:wrap}}@media(max-width:560px){.metrics{grid-template-columns:1fr}.run-form,.toolbar{align-items:stretch;flex-direction:column}.run-form button{margin-top:4px}}
  `]
})
export class BillsComponent implements OnChanges {
  @Input({required:true}) token=''; bills:Bill[]=[]; period=''; dueDate=''; query=''; statusFilter='All'; loading=false; generating=false; message=''; isError=false;
  constructor(private http:HttpClient){}
  ngOnChanges(){if(this.token)this.load()}
  private headers(){return new HttpHeaders({Authorization:`Bearer ${this.token}`})}
  get filtered(){const query=this.query.trim().toLowerCase();return this.bills.filter(bill=>(this.statusFilter==='All'||bill.status===this.statusFilter)&&(!query||`${bill.referenceNumber} ${bill.unitNumber}`.toLowerCase().includes(query)))}
  get totalAmount(){return this.bills.reduce((sum,bill)=>sum+bill.totalAmount,0)}
  get outstanding(){return this.bills.reduce((sum,bill)=>sum+bill.outstandingBalance,0)}
  get paidCount(){return this.bills.filter(bill=>bill.status==='Paid').length}
  load(){this.loading=true;this.http.get<Bill[]>('http://localhost:5112/api/admin/bills',{headers:this.headers()}).subscribe({next:bills=>{this.bills=bills;this.loading=false},error:()=>{this.loading=false;this.message='Unable to load bills.';this.isError=true}})}
  generate(){if(!/^\d{4}-\d{2}$/.test(this.period)||!this.dueDate){this.message='Enter a billing period in YYYY-MM format and a due date.';this.isError=true;return}this.generating=true;this.message='';this.http.post<{billsGenerated:number}>('http://localhost:5112/api/admin/bills/generate',{billingPeriod:this.period,dueDate:this.dueDate},{headers:this.headers()}).subscribe({next:result=>{this.generating=false;this.message=`${result.billsGenerated} bill(s) generated successfully.`;this.isError=false;this.load()},error:error=>{this.generating=false;this.message=error.status===409?'Bills have already been generated for this period.':'Unable to generate bills.';this.isError=true}})}
}
