import { DatePipe, DecimalPipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Dispute {
  disputeId:number; residentName:string; unitNumber:string; billReferenceNumber:string; billingPeriod:string;
  totalAmount:number; outstandingBalance:number; reason:string; status:'Open'|'UnderReview'|'Resolved'|'Rejected';
  submittedAt:string; resolvedAt?:string; adminResponse?:string;
}

@Component({
  selector:'app-disputes',standalone:true,imports:[FormsModule,DatePipe,DecimalPipe],
  template:`
    <section class="metrics"><article><span>Total disputes</span><strong>{{disputes.length}}</strong><small>All submitted records</small></article><article><span>Open</span><strong class="yellow">{{openCount}}</strong><small>Awaiting review</small></article><article><span>Under review</span><strong class="blue">{{underReviewCount}}</strong><small>Admin is investigating</small></article><article><span>Closed</span><strong class="green">{{closedCount}}</strong><small>Resolved or rejected</small></article></section>
    <section class="panel"><div class="head"><div><h2>Billing disputes</h2><p>Review resident disputes with the related bill period and bill reference.</p></div><button class="outline" (click)="load()" [disabled]="loading">{{loading?'Refreshing...':'Refresh'}}</button></div>
      @if(message){<p class="message" [class.error]="isError">{{message}}</p>}
      <div class="toolbar"><input [(ngModel)]="query" placeholder="Search resident, unit, bill, or period..."><select [(ngModel)]="statusFilter"><option value="All">All statuses</option><option value="Open">Open</option><option value="UnderReview">Under review</option><option value="Resolved">Resolved</option><option value="Rejected">Rejected</option></select></div>
      @if(loading){<p class="empty">Loading disputes...</p>} @else if(!filtered.length){<p class="empty">No disputes match this filter.</p>} @else {<div class="table-wrap"><table><thead><tr><th>Resident</th><th>Unit</th><th>Billing period</th><th>Bill reference</th><th>Outstanding</th><th>Reason</th><th>Status</th><th>Admin action</th></tr></thead><tbody>@for(dispute of filtered;track dispute.disputeId){<tr><td><b>{{dispute.residentName}}</b><small>Submitted {{dispute.submittedAt|date:'mediumDate'}}</small></td><td>{{dispute.unitNumber}}</td><td><b class="period">{{dispute.billingPeriod}}</b><small>Total RM {{dispute.totalAmount|number:'1.2-2'}}</small></td><td><span class="reference">{{dispute.billReferenceNumber}}</span></td><td [class.alert]="dispute.outstandingBalance>0">RM {{dispute.outstandingBalance|number:'1.2-2'}}</td><td class="reason">{{dispute.reason}}</td><td><span class="status" [class.review]="dispute.status==='UnderReview'" [class.closed]="dispute.status==='Resolved'" [class.rejected]="dispute.status==='Rejected'">{{label(dispute.status)}}</span></td><td>@if(dispute.status==='Open'||dispute.status==='UnderReview'){<div class="review"><select [(ngModel)]="decisions[dispute.disputeId]"><option value="UnderReview">Under review</option><option value="Resolved">Resolve</option><option value="Rejected">Reject</option></select><input [(ngModel)]="responses[dispute.disputeId]" maxlength="500" placeholder="Response required to close"><button (click)="review(dispute)" [disabled]="reviewing===dispute.disputeId">{{reviewing===dispute.disputeId?'Saving...':'Save'}}</button></div>}@else{<span class="response">{{dispute.adminResponse||'Closed'}}</span>}</td></tr>}</tbody></table></div>}
    </section>
  `,
  styles:[`
    :host{display:block}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:26px 0}.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.metrics article{padding:19px}.metrics span,.metrics small{display:block;color:#8fa0ba;font-size:.8rem}.metrics strong{display:block;color:#edf3ff;font-size:1.55rem;margin:13px 0 5px}.metrics .yellow{color:#ffbf55}.metrics .blue{color:#69a4ff}.metrics .green{color:#42d9a3}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.head button,.review button{border:0;border-radius:8px;padding:10px 12px;color:#fff;font-weight:700;cursor:pointer}.head .outline{background:transparent;border:1px solid #3b4d6b;color:#a9c5f7}.head button:disabled,.review button:disabled{opacity:.6;cursor:wait}.message{margin:15px 0;color:#47dca8;font-size:.85rem;font-weight:700}.message.error{color:#ff9292}.toolbar{display:flex;gap:12px;margin:22px 0}.toolbar input,.toolbar select,.review input,.review select{box-sizing:border-box;padding:10px 11px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.toolbar input{flex:1}.toolbar select{min-width:170px}.table-wrap{overflow:auto}table{width:100%;min-width:1300px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7;vertical-align:middle}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}td b{color:#eef4ff}td small{display:block;color:#71839c;font-size:.7rem;margin-top:4px}.period{color:#eaf1ff}.reference{display:block;color:#72a8ff;font-family:ui-monospace,monospace;font-size:.76rem}.alert{color:#ff9a9a}.reason{min-width:180px;max-width:270px;line-height:1.4}.status{display:inline-block;padding:4px 9px;border-radius:10px;background:#493a18;color:#ffc75d;font-size:.77rem}.status.review{background:#1d365e;color:#78adff}.status.closed{background:#103b30;color:#47dca8}.status.rejected{background:#51262b;color:#ff9999}.review{display:grid;grid-template-columns:130px minmax(170px,1fr) auto;gap:7px;align-items:center;min-width:400px}.review button{background:#347cf2}.response{display:block;max-width:230px;color:#aab8cb;font-size:.78rem;line-height:1.4}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.metrics{grid-template-columns:1fr}.head,.toolbar{align-items:flex-start;flex-direction:column}.toolbar input,.toolbar select{width:100%}}
  `]
})
export class DisputesComponent implements OnChanges {
  @Input({required:true}) token=''; disputes:Dispute[]=[]; query=''; statusFilter='All'; loading=false; reviewing:number|null=null; message=''; isError=false; decisions:Record<number,string>={}; responses:Record<number,string>={};
  constructor(private http:HttpClient){}
  ngOnChanges(){if(this.token)this.load()}
  private headers(){return new HttpHeaders({Authorization:`Bearer ${this.token}`})}
  get filtered(){const text=this.query.trim().toLowerCase();return this.disputes.filter(dispute=>(this.statusFilter==='All'||dispute.status===this.statusFilter)&&(!text||`${dispute.residentName} ${dispute.unitNumber} ${dispute.billReferenceNumber} ${dispute.billingPeriod}`.toLowerCase().includes(text)))}
  get openCount(){return this.disputes.filter(dispute=>dispute.status==='Open').length} get underReviewCount(){return this.disputes.filter(dispute=>dispute.status==='UnderReview').length} get closedCount(){return this.disputes.filter(dispute=>dispute.status==='Resolved'||dispute.status==='Rejected').length}
  label(status:string){return status==='UnderReview'?'Under review':status}
  load(){this.loading=true;this.http.get<Dispute[]>('http://localhost:5112/api/admin/disputes',{headers:this.headers()}).subscribe({next:data=>{this.disputes=data;for(const dispute of data)if(!this.decisions[dispute.disputeId])this.decisions[dispute.disputeId]=dispute.status==='Open'?'UnderReview':dispute.status;this.loading=false},error:()=>{this.loading=false;this.message='Unable to load disputes.';this.isError=true}})}
  review(dispute:Dispute){const status=this.decisions[dispute.disputeId]||'UnderReview';const response=this.responses[dispute.disputeId]?.trim()||'';if((status==='Resolved'||status==='Rejected')&&!response){this.message='Add an admin response before closing a dispute.';this.isError=true;return}this.reviewing=dispute.disputeId;this.message='';this.http.put(`http://localhost:5112/api/admin/disputes/${dispute.disputeId}/review`,{status,adminResponse:response||null},{headers:this.headers()}).subscribe({next:()=>{this.reviewing=null;this.message='Dispute updated successfully.';this.isError=false;this.load()},error:error=>{this.reviewing=null;this.message=error.error?.message||'Unable to update this dispute.';this.isError=true}})}
}
