import { DecimalPipe } from '@angular/common';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, Input, OnChanges } from '@angular/core';
import { FormsModule } from '@angular/forms';

interface Reminder { residentName:string; unitNumber:string; billReference:string; outstandingAmount:number; daysOverdue:number; reminderSent:boolean; }

@Component({
  selector:'app-reminders',standalone:true,imports:[DecimalPipe,FormsModule],
  template:`
    <section class="metrics"><article><span>Overdue accounts</span><strong>{{reminders.length}}</strong><small>Residents requiring attention</small></article><article><span>Total outstanding</span><strong class="red">RM {{totalOutstanding|number:'1.2-2'}}</strong><small>Across overdue bills</small></article><article><span>Reminders sent</span><strong class="green">{{sentCount}}</strong><small>Already notified</small></article><article><span>Awaiting reminder</span><strong class="yellow">{{pendingCount}}</strong><small>Ready to send</small></article></section>
    <section class="panel"><div class="head"><div><h2>Overdue payment reminders</h2><p>Review overdue residents, then send the reminder notification.</p></div><button (click)="send()" [disabled]="sending||!reminders.length">{{sending?'Sending reminders...':'Send overdue reminders'}}</button></div>@if(message){<p class="message" [class.error]="isError">{{message}}</p>}<div class="toolbar"><input [(ngModel)]="query" placeholder="Search resident, unit, or bill..."><button class="outline" (click)="load()">Refresh</button></div>@if(loading){<p class="empty">Loading overdue accounts...</p>}@else if(!filtered.length){<p class="empty">No overdue accounts match your search.</p>}@else{<div class="table-wrap"><table><thead><tr><th>Resident</th><th>Unit</th><th>Bill reference</th><th>Outstanding</th><th>Days overdue</th><th>Reminder status</th></tr></thead><tbody>@for(item of filtered;track item.billReference+item.residentName){<tr><td><b>{{item.residentName}}</b></td><td>{{item.unitNumber}}</td><td>{{item.billReference}}</td><td class="amount">RM {{item.outstandingAmount|number:'1.2-2'}}</td><td><span class="days" [class.high]="item.daysOverdue>60" [class.medium]="item.daysOverdue>30&&item.daysOverdue<=60">{{item.daysOverdue}} days</span></td><td><span class="status" [class.pending]="!item.reminderSent">{{item.reminderSent?'Sent':'Not sent'}}</span></td></tr>}</tbody></table></div>}</section>
  `,
  styles:[`
    :host{display:block}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin:26px 0}.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.metrics article{padding:19px}.metrics span,.metrics small{display:block;color:#8fa0ba;font-size:.8rem}.metrics strong{display:block;color:#edf3ff;font-size:1.45rem;margin:13px 0 5px}.metrics .red{color:#ff8585}.metrics .green{color:#42d9a3}.metrics .yellow{color:#ffbf55}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:center;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.head button,.toolbar button{border:0;border-radius:8px;padding:11px 15px;background:#347cf2;color:#fff;font-weight:700;cursor:pointer}.head button:disabled{opacity:.6}.message{margin:15px 0;color:#47dca8;font-weight:700;font-size:.85rem}.message.error{color:#ff9292}.toolbar{display:flex;gap:12px;margin:22px 0}.toolbar input{flex:1;box-sizing:border-box;padding:11px 12px;border:1px solid #34435e;background:#101624;border-radius:8px;color:#eef4ff;font:inherit}.toolbar .outline{background:transparent;border:1px solid #3b4d6b;color:#a9c5f7}.table-wrap{overflow:auto}table{width:100%;min-width:800px;border-collapse:collapse}th,td{text-align:left;padding:14px 12px;border-top:1px solid #2a364c;color:#cbd6e7}th{color:#8293ae;font-size:.76rem;text-transform:uppercase;letter-spacing:.04em}td b{color:#eef4ff}.amount{color:#ffaaaa}.days,.status{display:inline-block;padding:4px 9px;border-radius:10px;background:#1d365e;color:#78adff;font-size:.77rem}.days.medium{background:#493a18;color:#ffc75d}.days.high{background:#51262b;color:#ff9999}.status{background:#103b30;color:#47dca8}.status.pending{background:#493a18;color:#ffc75d}.empty{padding:28px 0;color:#8495ad;text-align:center}@media(max-width:900px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.metrics{grid-template-columns:1fr}.head,.toolbar{align-items:flex-start;flex-direction:column}.toolbar input{width:100%}}
  `]
})
export class RemindersComponent implements OnChanges {
  @Input({required:true}) token='';reminders:Reminder[]=[];sending=false;loading=false;message='';isError=false;query='';
  constructor(private http:HttpClient){}
  ngOnChanges(){this.load()} headers(){return new HttpHeaders({Authorization:`Bearer ${this.token}`})}
  get filtered(){const value=this.query.trim().toLowerCase();return value?this.reminders.filter(item=>`${item.residentName} ${item.unitNumber} ${item.billReference}`.toLowerCase().includes(value)):this.reminders}
  get totalOutstanding(){return this.reminders.reduce((sum,item)=>sum+item.outstandingAmount,0)} get sentCount(){return this.reminders.filter(item=>item.reminderSent).length} get pendingCount(){return this.reminders.filter(item=>!item.reminderSent).length}
  load(){if(!this.token)return;this.loading=true;this.http.get<Reminder[]>('http://localhost:5112/api/admin/reminders/overdue',{headers:this.headers()}).subscribe({next:data=>{this.reminders=data;this.loading=false},error:()=>{this.message='Unable to load overdue accounts.';this.isError=true;this.loading=false}})}
  send(){this.sending=true;this.message='';this.http.post<{remindersSent:number}>('http://localhost:5112/api/admin/reminders/overdue',{}, {headers:this.headers()}).subscribe({next:result=>{this.message=`${result.remindersSent} reminder(s) sent.`;this.isError=false;this.sending=false;this.load()},error:()=>{this.message='Unable to send reminders.';this.isError=true;this.sending=false}})}
}
