import { DecimalPipe } from '@angular/common';
import { Component, Input, OnChanges } from '@angular/core';
import { AdminApiService } from './admin-api.service';
import { AgingSummary } from './admin-types';

@Component({
  selector:'app-reports',standalone:true,imports:[DecimalPipe],
  template:`
    @if(summary){
      <section class="metrics"><article><span>Total outstanding</span><strong>RM {{summary.totalOutstanding|number:'1.2-2'}}</strong><small>All unpaid balances</small></article><article><span>1-30 days</span><strong class="blue">RM {{summary.days1To30|number:'1.2-2'}}</strong><small>Recently overdue</small></article><article><span>31-60 days</span><strong class="yellow">RM {{summary.days31To60|number:'1.2-2'}}</strong><small>Follow up required</small></article><article><span>61-90 days</span><strong class="orange">RM {{summary.days61To90|number:'1.2-2'}}</strong><small>High priority</small></article><article><span>Over 90 days</span><strong class="red">RM {{summary.over90Days|number:'1.2-2'}}</strong><small>Immediate attention</small></article></section>
      <section class="panel"><div class="head"><div><h2>Aging report</h2><p>Outstanding balances grouped by payment age.</p></div><span class="tag">Live report</span></div><div class="aging-list">@for(bucket of buckets;track bucket.label){<div class="age-row"><div><b>{{bucket.label}}</b><span>{{bucket.note}}</span></div><div class="track"><i [class]="bucket.color" [style.width.%]="bucket.percent"></i></div><strong [class.urgent]="bucket.color==='red'">RM {{bucket.amount|number:'1.2-2'}}</strong></div>}</div><div class="report-total"><span>Total outstanding balance</span><strong>RM {{summary.totalOutstanding|number:'1.2-2'}}</strong></div></section>
    }@else{<p class="loading">Loading aging report...</p>}
  `,
  styles:[`
    :host{display:block}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:15px;margin:26px 0}.metrics article,.panel{background:#171e2d;border:1px solid #2a3854;border-radius:15px;box-shadow:0 12px 30px #070a1026}.metrics article{padding:18px}.metrics span,.metrics small{display:block;color:#8fa0ba;font-size:.78rem}.metrics strong{display:block;color:#edf3ff;font-size:1.25rem;margin:13px 0 5px;letter-spacing:-.03em}.metrics strong.blue{color:#69a4ff}.metrics strong.yellow{color:#ffbf55}.metrics strong.orange{color:#ff8e3a}.metrics strong.red{color:#ff8585}.panel{padding:22px}.head{display:flex;justify-content:space-between;align-items:start;gap:16px}.head h2{margin:0;color:#eef4ff;font-size:1.1rem}.head p{margin:6px 0 0;color:#8293ae;font-size:.83rem}.tag{padding:5px 9px;border-radius:999px;background:#183b72;color:#78adff;font-size:.72rem}.aging-list{margin-top:25px}.age-row{display:grid;grid-template-columns:130px 1fr 135px;align-items:center;gap:18px;padding:17px 0;border-top:1px solid #2a364c}.age-row b{display:block;color:#e9f0fc;font-size:.9rem}.age-row span{display:block;color:#7e90aa;font-size:.74rem;margin-top:4px}.track{height:10px;border-radius:10px;background:#101624;overflow:hidden}.track i{display:block;height:100%;border-radius:10px}.track .green{background:#24c891}.track .blue{background:#3d82f6}.track .yellow{background:#f3b328}.track .orange{background:#fa7c29}.track .red{background:#f05252}.age-row strong{text-align:right;color:#dce6f7;font-size:.9rem}.age-row strong.urgent{color:#ff8585}.report-total{display:flex;justify-content:space-between;align-items:center;border-top:1px solid #3a4a66;margin-top:6px;padding:19px 0 2px;color:#abb8ca}.report-total strong{color:#eef4ff;font-size:1.2rem}.loading{padding:38px 0;color:#8495ad}@media(max-width:1050px){.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,1fr)}.age-row{grid-template-columns:1fr;gap:8px}.age-row strong{text-align:left}}@media(max-width:450px){.metrics{grid-template-columns:1fr}}
  `]
})
export class ReportsComponent implements OnChanges {
  @Input({required:true}) token='';summary:AgingSummary|null=null;
  constructor(private api:AdminApiService){}
  ngOnChanges(){if(this.token)this.api.agingSummary(this.token).subscribe(data=>this.summary=data)}
  get buckets(){const s=this.summary;const total=s?.totalOutstanding||1;return[{label:'Current',note:'Not yet overdue',amount:s?.current??0,color:'green'},{label:'1-30 days',note:'Recently overdue',amount:s?.days1To30??0,color:'blue'},{label:'31-60 days',note:'Follow-up required',amount:s?.days31To60??0,color:'yellow'},{label:'61-90 days',note:'High priority',amount:s?.days61To90??0,color:'orange'},{label:'Over 90 days',note:'Immediate attention',amount:s?.over90Days??0,color:'red'}].map(item=>({...item,percent:Math.min(100,item.amount/total*100)}))}
}
