import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import { ReceiptDetail } from '@/services/receipts/receiptsService';
import { escapeHtml } from '@/utils/escapeHtml';
import { formatBillingPeriod, formatShortDate } from '@/utils/formatDate';

type ReceiptPdfInput = {
  receipt: ReceiptDetail;
  residentName: string;
};

// Same print-appropriate styling rationale as generateBillPdf.ts — white background, system
// fonts only (expo-print's WebView/print engine can't reliably fetch the app's Google Fonts).
function buildReceiptHtml({ receipt, residentName }: ReceiptPdfInput): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: Georgia, 'Times New Roman', serif;
    color: #221C18;
    padding: 40px 48px;
  }
  .sans { font-family: Helvetica, Arial, sans-serif; }
  .masthead {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 3px solid #7CB596;
    padding-bottom: 16px;
    margin-bottom: 20px;
  }
  .brand { font-size: 22px; font-weight: 700; color: #D67D5C; letter-spacing: 0.5px; }
  .doc-title {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 11px;
    letter-spacing: 1.5px;
    text-transform: uppercase;
    color: #6B6258;
    margin-top: 4px;
  }
  .meta-right { text-align: right; }
  .label {
    font-size: 10px;
    letter-spacing: 1px;
    text-transform: uppercase;
    color: #6B6258;
    margin-bottom: 3px;
  }
  .value { font-size: 13px; color: #221C18; margin-bottom: 10px; }
  .value.muted { color: #6B6258; font-size: 12px; }
  .mono { font-family: 'Courier New', monospace; }
  .confirmed-banner {
    display: flex;
    align-items: center;
    gap: 10px;
    background: #EAF3EE;
    border: 1px solid #7CB596;
    border-radius: 8px;
    padding: 14px 18px;
    margin-bottom: 24px;
  }
  .confirmed-check {
    width: 22px;
    height: 22px;
    border-radius: 11px;
    background: #7CB596;
    color: #fff;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 13px;
    font-weight: 700;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  .confirmed-text {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 13px;
    font-weight: 700;
    color: #3E7A5C;
  }
  .meta-grid {
    display: flex;
    justify-content: space-between;
    margin-bottom: 24px;
    font-family: Helvetica, Arial, sans-serif;
  }
  .amount-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-top: 2px solid #221C18;
    border-bottom: 2px solid #221C18;
    margin-bottom: 24px;
    padding: 14px 0;
    font-family: Helvetica, Arial, sans-serif;
  }
  .amount-row span:first-child { font-size: 14px; font-weight: 700; }
  .amount-value { font-size: 24px; font-weight: 700; color: #7CB596; font-family: 'Courier New', monospace; }
  .footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #EDE8E0;
    font-family: Helvetica, Arial, sans-serif;
    font-size: 10px;
    color: #6B6258;
    text-align: center;
  }
</style>
</head>
<body>
  <div class="masthead">
    <div>
      <div class="brand">PropertyBill</div>
      <div class="doc-title">Payment Receipt</div>
    </div>
    <div class="meta-right">
      <div class="label">Receipt No.</div>
      <div class="value mono">${escapeHtml(receipt.receiptNumber)}</div>
    </div>
  </div>

  <div class="confirmed-banner">
    <div class="confirmed-check">&#10003;</div>
    <div class="confirmed-text">Payment Confirmed</div>
  </div>

  <div class="meta-grid">
    <div>
      <div class="label">Received From</div>
      <div class="value">${escapeHtml(residentName)}</div>
      <div class="value muted">Unit ${escapeHtml(receipt.unitNumber)} &middot; ${escapeHtml(receipt.propertyName)}</div>
    </div>
    <div class="meta-right">
      <div class="label">Payment Date</div>
      <div class="value">${formatShortDate(receipt.paymentDate)}</div>
      <div class="label">Payment Method</div>
      <div class="value">${escapeHtml(receipt.channel)}</div>
    </div>
  </div>

  <div>
    <div class="label">For Bill</div>
    <div class="value mono">${escapeHtml(receipt.billReferenceNumber)}</div>
    <div class="value muted">${formatBillingPeriod(receipt.billingPeriod)}</div>
  </div>

  <div class="amount-row">
    <span>Amount Paid</span>
    <span class="amount-value">RM ${receipt.amount.toFixed(2)}</span>
  </div>

  <div class="footer">
    Generated by PropertyBill on ${formatShortDate(new Date().toISOString())} &middot; This is a system-generated payment receipt.
  </div>
</body>
</html>`;
}

// Same on-device flow and fix as generateAndShareBillPdf: share directly from the
// printToFileAsync cache URI rather than touching expo-file-system at all — see that file's
// comment for why (renaming/copying via expo-file-system throws a READ-permission error on
// a physical Android device in Expo Go).
export async function generateAndShareReceiptPdf(input: ReceiptPdfInput): Promise<void> {
  try {
    const html = buildReceiptHtml(input);
    const { uri } = await Print.printToFileAsync({ html, base64: false });

    const filename = `Receipt_${input.receipt.receiptNumber}.pdf`;
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: filename,
        UTI: 'com.adobe.pdf',
      });
    }
  } catch (err) {
    console.error(
      '[generateAndShareReceiptPdf] failed:',
      err instanceof Error ? err.message : err,
      err instanceof Error ? err.stack : undefined
    );
    throw err;
  }
}
